// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8PIuFotw1lSUvvaFZGJhOyk4OOclo-w',
    appId: '1:974393354551:web:764743e670ebbe05c612b2',
    messagingSenderId: '974393354551',
    projectId: 'learn-database-25308',
    authDomain: 'learn-database-25308.firebaseapp.com',
    storageBucket: 'learn-database-25308.appspot.com',
    measurementId: 'G-2D9H7D18L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNuVnlAAwnzS3g4-JsulTUXDs65KGVUHo',
    appId: '1:974393354551:android:d94a26dc17368ba7c612b2',
    messagingSenderId: '974393354551',
    projectId: 'learn-database-25308',
    storageBucket: 'learn-database-25308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEVtcjkEgj2buzXWiTf5if6me6WfVNdek',
    appId: '1:974393354551:ios:5f542543848a44f2c612b2',
    messagingSenderId: '974393354551',
    projectId: 'learn-database-25308',
    storageBucket: 'learn-database-25308.appspot.com',
    iosBundleId: 'com.pdp.learnFl22CloudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEVtcjkEgj2buzXWiTf5if6me6WfVNdek',
    appId: '1:974393354551:ios:db4c84de003ff333c612b2',
    messagingSenderId: '974393354551',
    projectId: 'learn-database-25308',
    storageBucket: 'learn-database-25308.appspot.com',
    iosBundleId: 'com.pdp.learnFl22CloudFirestore.RunnerTests',
  );
}
